@host=https://localhost:5001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJTaW1vbiIsImZhbWlseV9uYW1lIjoiUmlsZXkiLCJqdGkiOiI1ZDNjNDE2ZC1hYmY5LTQxNGItYWZjYi1mMjE1MTI0YWY1M2UiLCJleHAiOjE3MDY1MzUzMTUsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.LIZmW4CNSp3Krbcsz24jsReJyT3Hxvfbld7N0P-htTI
@hostId=0be0e41b-e7ea-467c-8d4d-ef42c38c280f

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}